/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import javafx.application.Application;
import javafx.scene.Group;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.awt.*;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    @Override
    public void start(Stage stage) throws Exception{
        stage.setTitle("Course View");
        Label label = new Label("Students");
        Label courseLabel = new Label("Courses");
        stage.show();
    }

    public static void main(String[] args) {
        Application.launch(args);
    }
}
